name: Deploy to Development

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy frontend to dev
    runs-on: [self-hosted]
    environment: development
    
    steps:         
      - name: Deploy new version
        run: |
          sudo apt-get install sshpass
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          eval $(ssh-agent)
          ssh-add ~/.ssh/github_intratechconsulting
          cd ~/TestServer/frontend
          docker compose down
          git checkout development
          git pull
          docker compose up --build -d
          ENDSSH
