name: Deploy to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy frontend to dev
    runs-on: [self-hosted]
    environment: staging
  
    steps:
      - name: Deploy new version
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          eval $(ssh-agent)
          ssh-add ~/.ssh/github_intratechconsulting
          cd ~/staging/frontend
          docker compose down
          docker rmi crm/api-publisher-consumer:latest
          git checkout staging
          git pull
          docker compose up -d
          ENDSSH
